# -*- coding: utf-8 -*-
"""Project สัมนา Model YOLO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oqu1KqN5-IecdYjEMBy-pHS1c7LDgjTP

# LOAD TRAIN AND TEST DATA
"""

!gdown 1D_BXNyR2cCgF07V6scHrFlbxIO_CfzpA

!unzip /content/Insect.zip

"""# YOLO V5"""

## Clone repository
!git clone https://github.com/ultralytics/yolov5
## Change directory to yolov5
!cd yolov5
## install required library
!pip install -r /content/yolov5/requirements.txt  # install

!python /content/yolov5/train.py --img 640 --batch 16 --epochs 100 --data /content/Insect/data.yaml --weights yolov5s.pt

!python /content/yolov5/detect.py --weights yolov5s.pt --weights /content/yolov5/runs/train/exp/weights/best.pt --source /content/TestVideo

"""# YOLO v8"""

!pip install ultralytics

from ultralytics import YOLO


model = YOLO('yolov8n.yaml')
model = YOLO('yolov8n.pt')
model = YOLO('yolov8n.yaml').load('yolov8n.pt')

results = model.train(data='/content/Insect/data.yaml', epochs=100, imgsz=640)

model = YOLO('yolov8n.pt')
model = YOLO('/content/runs/detect/train/weights/best.pt')

model.predict('/content/TestVideo', save=True, imgsz=640, conf=0.5)

import shutil

shutil.rmtree('/content/yolov5/runs/detect/exp2')